### PR TITLE
CSV Header Fix, Progress Status fixes

### LINKED ISSUE #48: Failing on create experiment triggers processing fail in UI
Since the "create experiment" function is called last, if it fails, it will automatically fail on the last processing piece instead of failing in some sort of "separate" step. So the UI will show that the last process has failed rather than just the "createExperiment" function has failed.

### PR DESCRIPTION
**Pull request by bbollen23**
### Does this PR close any open issues?
Closes #48, #54

### Give a longer description of what this PR addresses and why it's needed
- Header choices are now refreshed whenever the table files change rather than when the column mapping page is activated (using onActivated)
- A new progress has been added: Create Experiment. This happens after the processing
- SubmitExperiment is now called via a watch variable in the upload store rather than inside checkForUpdates
- "DetermineProgress" function which determines the overall progress of a step is now in a computed variable.
- Refactored some of the loading progress code. Now, it is a bit more clear what happens: the raw list of porgresses is initialized (with the values that are specific to what we're doing), then a generic computed variable is outputted which changes the status of a progressRecord depdendent on its subProgresses. Finally, another watch is added to check if all steps have completed, some are still running, or any have failed. This then changes the messaging on the right. 

### Provide pictures/videos of the behavior before and after these changes (optional)
Screenshot 2024-08-07 at 4 37 54 PM (2)

### CODE REVIEW

File: apps/client/src/components/upload/StepColumnNameMapping.vue [hunk 1]
```diff
@@ -46,10 +46,10 @@ const specialVariables = ref<SpecialVariable[]>([
...
 ]);
 
-onActivated(() => {
-    console.log('hook called');
-    uploadStore.populateDefaultColumnMappings();
-});
+// onActivated(() => {
+//     console.log('hook called');
+//     uploadStore.populateDefaultColumnMappings();
+// });
```
Comment (Dev-Lan) [inline apps/client/src/components/upload/StepColumnNameMapping.vue:52]:
```suggestion
```

**Review by Dev-Lan — CHANGES_REQUESTED** [review]
Super small requested changes.

**Comment by Dev-Lan** [comment]
I ran into another issue that I don't have time to fully investigate, but I want to write it down before I forget. The upload worked, but the the visualizations ran into issues when loading the new data. It looks like the issue is with file paths for the imaging data. My first guess may have to do with the difference between a zipped folder and a zipped collection of files again.

Basically the images were all in minio, but he experiment json file I think was missing a directory in the path.

**Review by Dev-Lan — APPROVED** [review]
